version: '3.4'

services:
  aspnetcoremicroservices.customers:
    image: ${DOCKER_REGISTRY}aspnetcoremicroservicescustomers
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.Customers/Dockerfile

  aspnetcoremicroservices.products:
    image: ${DOCKER_REGISTRY}aspnetcoremicroservicesproducts
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.Products/Dockerfile


  aspnetcoremicroservices.apigateway:
    image: ${DOCKER_REGISTRY}aspnetcoremicroservicesapigateway
    build:
      context: .
      dockerfile: AspNetCoreMicroservices.ApiGateway/Dockerfile


  angularwebui:
    image: ${DOCKER_REGISTRY}angularwebui
    build:
      context: .
      dockerfile: AngularWebUI/Dockerfile

